#coding=utf-8
from django.db import models


class Male(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("姓名", max_length=32)
    gender = models.CharField("性别", max_length=10)
    job = models.CharField("职业", max_length=32)
    hobby = models.CharField("爱好", max_length=63)
    fname = models.CharField("法名", max_length=32)
    birthday = models.CharField("生日", max_length=32)
    personnel_id = models.CharField("身份证号", max_length=32)
    phone_num = models.CharField("手机号", max_length=20)
    race = models.CharField("民族", max_length=20)
    degree = models.CharField("学历", max_length=32)
    health = models.CharField("健康情况", max_length=32)
    telephone_num = models.CharField("固定电话", max_length=20)
    workplace = models.CharField("工作单位", max_length=64)
    province = models.CharField("现居地址（省)", max_length=64)
    city = models.CharField("现居地址（市)", max_length=64)
    district = models.CharField("现居地址（县)", max_length=64)
    address = models.CharField("现居地址（乡镇/小区/街道)", max_length=64)
    postcode = models.CharField("邮政编码", max_length=64)
    graduate_time = models.CharField('毕业时间', max_length=32)
    graduate_school = models.CharField('毕业学校', max_length=64)
    first_job_entry_time = models.CharField('工作起始时间一', max_length=32)
    first_job_workplace = models.CharField('工作单位一', max_length=64)
    second_job_entry_time = models.CharField('工作起始时间二', max_length=64)
    second_job_workplace = models.CharField('工作单位二', max_length=32)
    retirement_date = models.CharField('退休时间', max_length=32)
    retirement_workplace = models.CharField('退休单位', max_length=64)
    year2start_learning_buddhism = models.CharField('学佛起始时间', max_length=32)
    years_of_learning_buddhism = models.CharField('学佛时长', max_length=10)
    deep_understanding_of_dharma = models.CharField('是否深刻了解佛法', max_length=64)
    reason2learning_dharma = models.CharField('学佛因缘', max_length=128)
    nums_of_buddhism_book = models.CharField('读经典部数', max_length=32)
    easy2learn_buddhism_book = models.CharField('容易读懂的经典', max_length=128)
    hard2read = models.CharField('难学经典', max_length=128)
    maxim = models.CharField('格言', max_length=128)
    buddhist_disciples_of_family = models.CharField('家庭三宝弟子成员', max_length=128)
    ipaddress = models.CharField('IP 地址', max_length=32)
    comes = models.DecimalField('来自手机或者笔记本录入，0：笔记本， 1：手机', max_digits=5, decimal_places=0)

    def __unicode__(self):
        return self.name

class Female(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("姓名", max_length=32)
    gender = models.CharField("性别", max_length=10)
    job = models.CharField("职业", max_length=32)
    hobby = models.CharField("爱好", max_length=63)
    fname = models.CharField("法名", max_length=32)
    birthday = models.CharField("生日", max_length=32)
    personnel_id = models.CharField("身份证号", max_length=32)
    phone_num = models.CharField("手机号", max_length=20)
    race = models.CharField("民族", max_length=20)
    degree = models.CharField("学历", max_length=32)
    health = models.CharField("健康情况", max_length=32)
    telephone_num = models.CharField("固定电话", max_length=20)
    workplace = models.CharField("工作单位", max_length=64)
    province = models.CharField("现居地址（省)", max_length=64)
    city = models.CharField("现居地址（市)", max_length=64)
    district = models.CharField("现居地址（县)", max_length=64)
    address = models.CharField("现居地址（乡镇/小区/街道)", max_length=64)
    postcode = models.CharField("邮政编码", max_length=64)
    graduate_time = models.CharField('毕业时间', max_length=32)
    graduate_school = models.CharField('毕业学校', max_length=64)
    first_job_entry_time = models.CharField('工作起始时间一', max_length=32)
    first_job_workplace = models.CharField('工作单位一', max_length=64)
    second_job_entry_time = models.CharField('工作起始时间二', max_length=64)
    second_job_workplace = models.CharField('工作单位二', max_length=32)
    retirement_date = models.CharField('退休时间', max_length=32)
    retirement_workplace = models.CharField('退休单位', max_length=64)
    year2start_learning_buddhism = models.CharField('学佛起始时间', max_length=32)
    years_of_learning_buddhism = models.CharField('学佛时长', max_length=10)
    deep_understanding_of_dharma = models.CharField('是否深刻了解佛法', max_length=64)
    reason2learning_dharma = models.CharField('学佛因缘', max_length=128)
    nums_of_buddhism_book = models.CharField('读经典部数', max_length=32)
    easy2learn_buddhism_book = models.CharField('容易读懂的经典', max_length=128)
    hard2read = models.CharField('难学经典', max_length=128)
    maxim = models.CharField('格言', max_length=128)
    buddhist_disciples_of_family = models.CharField('家庭三宝弟子成员', max_length=128)
    ipaddress = models.CharField('IP 地址', max_length=32)
    comes = models.DecimalField('来自手机或者笔记本录入，0：笔记本， 1：手机', max_digits=5, decimal_places=0)

    def __unicode__(self):
        return self.name

class Xiaozu(models.Model):
    name = models.CharField("姓名", max_length=32)
    gender = models.CharField("性别", max_length=10)
    phone_num = models.CharField("手机号", max_length=32)
    birthday = models.CharField("生日", max_length=32)
    address = models.CharField("现居地址（乡镇/小区/街道)", max_length=128)
    xiaozu_type = models.CharField("小组类型", max_length=32)
    xiaozu_lang = models.CharField("小组语言种类", max_length=32)
    xiaozu_dizhi = models.CharField("学佛小组地址", max_length=128)
    xiaozu_fou = models.CharField("是否参加学佛小组", max_length=128)


    def __unicode__(self):
        return self.name
